server:
  port: 5000
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 300
    accept-count: 100
    connection-timeout: 10000

spring:
  application:
    name: twitter
  main:
    lazy-initialization: true
  cache:
    type: caffeine

logging:
  pattern:
    console: "%msg%n"
  level:
    root: INFO
    com.bark.twitter: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99

synoptic:
  api:
    base-url: https://api.synoptic.com/twttr-api
    api-key: 1f0be122-a228-6700-b695-83f536d5a900
    connect-timeout-ms: 5000
    read-timeout-ms: 10000

twitterapi:
  api-key: new1_a8b0f543e0fc4a628a523c46e15b2575

security:
  api-keys:
    - 2e54206b02cb6ed997f42f5bb10d7d19ff59e80f19b334339d38d08a92fb1b71 # AXIOM

aws:
  region: us-east-1
  dynamodb:
    usage-table: twitter-relay-usage
